#!/usr/bin/env python
import csv
import sys
csv.field_size_limit(1000000000)
good_lines = 0
all_lines = 0
with open(sys.argv[1]) as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
    	all_lines+=1
        #"Year","Quarter","Month","DayofMonth","DayOfWeek","FlightDate","UniqueCarrier","AirlineID","Carrier","TailNum","FlightNum",
        #"OriginAirportID","OriginAirportSeqID","OriginCityMarketID","Origin","OriginCityName","OriginState","OriginStateFips","OriginStateName","OriginWac",
        #"DestAirportID","DestAirportSeqID","DestCityMarketID","Dest","DestCityName","DestState","DestStateFips","DestStateName","DestWac",
        #"CRSDepTime","DepTime","DepDelay","DepDelayMinutes","DepDel15","DepartureDelayGroups","DepTimeBlk","TaxiOut","WheelsOff",
        #"WheelsOn","TaxiIn","CRSArrTime","ArrTime","ArrDelay","ArrDelayMinutes","ArrDel15","ArrivalDelayGroups","ArrTimeBlk",
        #"Cancelled","CancellationCode","Diverted","CRSElapsedTime","ActualElapsedTime","AirTime","Flights","Distance","DistanceGroup","CarrierDelay","WeatherDelay","NASDelay","SecurityDelay",
        #"LateAircraftDelay","FirstDepTime","TotalAddGTime","LongestAddGTime",
        #"DivAirportLandings","DivReachedDest","DivActualElapsedTime","DivArrDelay","DivDistance","Div1Airport","Div1AirportID","Div1AirportSe
        if row['TailNum'] == "":
            row['TailNum'] = row['FlightNum'] 
            # duplicate FlightNum if TailNum not defined
        # removed Cancel and Diverted Fly    
        if row['Cancelled'] == "0.00" and row['Diverted'] == "0.00":
            print "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s" % (row['FlightDate'],row['DayOfWeek'],row['TailNum'],row['FlightNum'],row['DepTime'],row['ArrTime'],row['UniqueCarrier'],row['Origin'],row['Dest'],row['DepDelay'],row['ArrDelay'],row['DepDelayMinutes'],row['ArrDelayMinutes'])
            good_lines+=1
            #print row['FlightDate'],",",row['DayOfWeek'],",",row['TailNum'],",",row['FlightNum'],",",row['DepTime'],",",row['ArrTime'],",",row['UniqueCarrier'],",",row['Origin'],",",row['Dest'],",",row['DepDelay'],",",row['ArrDelay'],",",row['DepDelayMinutes'],",",row['ArrDelayMinutes']
            #output:
            #FlightDate,DayOfWeek,TailNum,FlightNum,DepTime,ArrTime,UniqueCarrier,Origin,Dest,DepDelay,ArrDelay,DepDelayMinutes,ArrDelayMinutes
			#     0          1       2      3         4        5        6           7     8     9         10          11           12



sys.stderr.write("good lines %d for %d lines\n" % (good_lines,all_lines))